---
description: This library is some annotations for auto_exporter library, see auto_exporter for more information.
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
environment:
  sdk: '>=2.12.0 <4.0.0'
homepage: https://github.com/normidar/auto_exporter
name: auto_exporter_annotation
topics:
  - package-management
  - package
  - export
  - exporter
  - code-generation
version: 1.0.3
