version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "packages/auto_exporter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "packages/auto_exporter"
    schedule:
      interval: "monthly"
