name: flutter_example
description: an application by normidar.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_exporter: ^1.4.8
  build_runner: ^2.4.6
  build_test: ^2.2.0


flutter:


